# Generated by Django 2.2.4 on 2019-08-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190802_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='extra_cheese',
        ),
    ]
