# Generated by Django 2.2.4 on 2019-08-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190803_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='type',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='type',
        ),
        migrations.RemoveField(
            model_name='subaddon',
            name='type',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
