# Generated by Django 2.2.4 on 2019-08-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190803_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaddon',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='subaddon',
            name='small_price',
        ),
    ]
