# Generated by Django 2.2.4 on 2019-08-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190804_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='orders.CartItem'),
        ),
    ]
