# Generated by Django 2.2.4 on 2019-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='in_cart', max_length=20),
        ),
    ]
