# Generated by Django 2.2.4 on 2019-08-06 02:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_total'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
                ('parents', django.db.models.manager.Manager()),
            ],
        ),
    ]
