# Generated by Django 2.2.4 on 2019-08-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20190806_0227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
            ],
        ),
    ]
